---
    - name: Set selinux to permissive mode
      selinux:
        policy: targeted
        state: permissive
      
    - name: Download node exporter
      ansible.builtin.unarchive:
        src: https://github.com/prometheus/node_exporter/releases/download/v1.1.2/node_exporter-1.1.2.linux-amd64.tar.gz
        dest: /usr/local/bin/
        remote_src: yes
        extra_opts: [--strip-components=1]


    - name: Added a consultant whose account you want to expire
      ansible.builtin.user:
        name: node_exporter
        shell: /bin/false
        system: yes
     
    - name: Create a system unit for node exporter
      blockinfile:
        path: /etc/systemd/system/node_exporter.service
        block: |
          [Unit]
          Description=Node Exporter
          After=network.target

          [Service]
          User=node_exporter
          Group=node_exporter
          Type=simple
          ExecStart=/usr/local/bin/node_exporter --collector.systemd

          [Install]
          WantedBy=multi-user.target
        create: true
        
    - name: force systemd to reread configs
      ansible.builtin.systemd:
        daemon_reload: yes
    
    - name: Enable and start the cluster services
      ansible.builtin.service:
        name: node_exporter.service
        enabled: yes
        state: started


