---
    - name: Yum update the system
      yum:
        name: "*"
        state: latest

    - name: docker installation
      command: "sh get-docker.sh"

    - command: "systemctl start docker"
    - command: "systemctl enable docker"
    - yum: 
        name: epel-release

    - name: installing pip
      yum: 
        name: python-pip

    - name: installing ansible module for managing docker
      pip: 
        name: docker

    - name: Ensure nginx packages are installed.
      yum:
        name:
          - nginx
        state: present

    - name: Ensure httpd-tools packages are installed.
      yum:
        name:
          - httpd-tools
        state: present
     
    - name: Create credentials folder.
      file:
        path: /etc/apache2
        state: directory
        recurse: yes
    
    - name: Creating user credentials.
      shell: sudo htpasswd -cb /etc/apache2/.htpasswd admin examplepassword

    - name: Copy nginx config.
      ansible.builtin.copy:
        src: ./nginx.conf
        dest: /etc/nginx/nginx.conf
        follow: yes
        
    - name: Start & enable nginx service.
      shell: |
        systemctl enable nginx && \
        systemctl start nginx

    - name: setup Nginx exporter.
      docker_container:
        name: Nginx_exporter
        image: nginx/nginx-prometheus-exporter:0.9.0
        ports:
          - "9113:9113"
        command: -nginx.scrape-uri http://10.47.100.11/stub_status

