---
    - name: Yum update the system
      yum:
        name: "*"
        state: latest

    - name: Download docker installation shell script
      get_url:
        url: https://get.docker.com
        dest: /get-docker.sh
        mode: '0555'

    - name: Run docker installation shell script
      ansible.builtin.script: /get-docker.sh

    - name: Enable docker service, and change the state to start
      ansible.builtin.service:
        name: docker
        enabled: yes
        state: started

    - name: installing pip
      yum: 
        name: python3-pip

    - name: installing ansible module for managing docker
      pip: 
        name: docker

    - name: Ensure nginx && httpd-tools packages are installed.
      yum:
        name:
          - nginx
          - httpd-tools

        state: present
  
    - name: Create credentials folder.
      file:
        path: /etc/apache2
        state: directory
        recurse: yes
    
    - name: Creating user credentials.
      shell: sudo htpasswd -cb /etc/apache2/.htpasswd admin examplepassword

    - name: Copy nginx config.
      ansible.builtin.copy:
        src: ./nginx.conf
        dest: /etc/nginx/nginx.conf
        follow: yes
        
    - name: Start & enable nginx service.
      ansible.builtin.service:
        name: nginx
        enabled: yes
        state: started
        
    - name: setup Nginx exporter.
      docker_container:
        name: Nginx_exporter
        image: nginx/nginx-prometheus-exporter:0.9.0
        ports:
          - "9113:9113"
        command: -nginx.scrape-uri http://10.47.100.11/stub_status

