---
    - name: Yum update the system
      yum:
        name: "*"
        state: latest
        
    - name: Ensure dnsmasq & iptables packages are installed.
      yum:
        name:
          - dnsmasq
          - iptables-services
        state: present
    
    - name: Enable iptables service, and change the state to start
      ansible.builtin.service:
        name: iptables
        enabled: yes
        state: started

    - name: Enable dnsmasq service, and change the state to start
      ansible.builtin.service:
        name: dnsmasq
        enabled: yes
        state: started

    - name: Copy dnsmasq config.
      ansible.builtin.copy:
        src: ./dnsmasq.conf
        dest: /etc/dnsmasq.conf
        follow: yes

    - name: Configuring dnsmasq with /etc/resolv.conf File
      copy: 
        content: 'nameserver 127.0.0.1' 
        dest: /etc/resolv.conf

    - name: Ensure resolv.conf is immutable.
      file:
        path: /etc/resolv.conf
        attr: i

    - name: Restart dnsmasq service
      ansible.builtin.service:
        name: dnsmasq
        state: restarted

    - name: Flush iptables existing rules
      ansible.builtin.iptables:
        chain: "{{ item }}"
        flush: yes
      with_items:  [ 'INPUT', 'FORWARD', 'OUTPUT' ]

    - name: Set ip masquerade rule
      ansible.builtin.iptables:
        table: nat
        chain: POSTROUTING
        out_interface: eth0
        jump: MASQUERADE
      become: yes

    - name: Enable ip forwarding
      sysctl:
          name: net.ipv4.ip_forward
          value: 1
          sysctl_set: yes
